[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KomaMRI = "6a340f8b-2cdf-4c04-99be-4953d9b66d0a"
KomaMRIBase = "d0bc0b20-b151-4d03-b2a4-6ca51751cb9c"
KomaMRICore = "4baa4f4d-2ae9-40db-8331-a7d1080e3f4e"
KomaMRIFiles = "fcf631a6-1c7e-4e88-9e64-b8888386d9dc"
KomaMRIPlots = "76db0263-63f3-4d26-bb9a-5dba378db904"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
